### ISSUE TITLE
DelegationError

### ISSUE THREAD

**Issue by SandNerd** [Brunomm/delegate_associations#1]
Basically following this simple tutorial:
http://astockwell.com/blog/2014/03/polymorphic-associations-in-rails-4-devise/
Using your gem, when I try:

``` ruby
# Create a record with nested attributes
Subscriber.create(
    :region          => 'West',
    :referrer        => 'John Smith',
    :email    => 'jd@example.com',
    :name     => 'Jane Doe',
    :password => 'foobar'
)
```

I get this error: `Module::DelegationError`

**Comment by Brunomm** [comment]
Helo, please specify your Ruby and Rails version for I do the tests.
If possible, describe your code in here too.

Thanks

**Comment by SandNerd** [comment]
Thanks for a quick reply. This is my ruby environment info:
rubygems version: 2.5.1
ruby version: 2.2.3 (2015-08-18 patchlevel 173) [x86_64-linux]
rails (4.2.5.1)

My code is identical to the tutorial I mentioned and the only difference is using your gem for delegation of attributes.

**Comment by SandNerd** [comment]
Hey there. Just wanted to let you know that I managed to make it work using [this gem](https://github.com/TylerRick/active_record_auto_build_associations). You basically just need to add `auto_build_association` in the child models referencing the polymorphic parent. The gem looks simple so you can easily include it within your gem, if you like.

Out of curiosity, did you build this gem to have multi table inheritance (that's what I'm doing) or something else?

**Comment by Brunomm** [comment]
Thanks @sahal2080 ,  now I understood the problem. The gem auto_build_association is very simple, you only need to do this in your model:

``` ruby
# models/subscriber.rb
class Subscriber < ActiveRecord::Base
    has_one :user, as: :meta, dependent: :destroy
    accepts_nested_attributes_for :user

   def user
        super || build_user
   end
end
```

So, I created this gem by a nececity in a project. Look:  http://pt.stackoverflow.com/questions/62750/como-modelar-com-heran%C3%A7a-uma-estrutura-de-pessoas#answer-63274.
